/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.RM2PT.acceleo.foodapp.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Customer
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Customer {
	/**
	 * The documentation of the attribute name.
	 * 
	 * @generated
	 */
	private String name;
	
	/**
	 * The documentation of the attribute address.
	 * 
	 * @generated
	 */
	private String address;
	
	/**
	 * The documentation of the attribute number.
	 * 
	 * @generated
	 */
	private String number;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Customer() {
		super();
	}
	/**
	 * The documentation of the method makeOrder.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String makeOrder() {
		// Start of user code for the body of makeOrder
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getName.
	 * 
	 * @generated
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * The documentation of the setter setName.
	 * 
	 * @generated
	 */
	public void setName(String newName) {
		this.name = newName;
	}
	
	/**
	 * The documentation of the getter getAddress.
	 * 
	 * @generated
	 */
	public String getAddress() {
		return this.address;
	}
	
	/**
	 * The documentation of the setter setAddress.
	 * 
	 * @generated
	 */
	public void setAddress(String newAddress) {
		this.address = newAddress;
	}
	
	/**
	 * The documentation of the getter getNumber.
	 * 
	 * @generated
	 */
	public String getNumber() {
		return this.number;
	}
	
	/**
	 * The documentation of the setter setNumber.
	 * 
	 * @generated
	 */
	public void setNumber(String newNumber) {
		this.number = newNumber;
	}
}
