/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.RM2PT.acceleo.foodapp.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class DeliveryDriver
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class DeliveryDriver {
	/**
	 * The documentation of the attribute name.
	 * 
	 * @generated
	 */
	private String name;
	
	/**
	 * The documentation of the attribute vehicle.
	 * 
	 * @generated
	 */
	private String vehicle;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public DeliveryDriver() {
		super();
	}
	/**
	 * The documentation of the method deliverFood.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public Date deliverFood() {
		// Start of user code for the body of deliverFood
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getName.
	 * 
	 * @generated
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * The documentation of the setter setName.
	 * 
	 * @generated
	 */
	public void setName(String newName) {
		this.name = newName;
	}
	
	/**
	 * The documentation of the getter getVehicle.
	 * 
	 * @generated
	 */
	public String getVehicle() {
		return this.vehicle;
	}
	
	/**
	 * The documentation of the setter setVehicle.
	 * 
	 * @generated
	 */
	public void setVehicle(String newVehicle) {
		this.vehicle = newVehicle;
	}
}
