/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.RM2PT.acceleo.foodapp.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class FoodApp
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class FoodApp {
	/**
	 * The documentation of the attribute username.
	 * 
	 * @generated
	 */
	private String username;
	
	/**
	 * The documentation of the attribute password.
	 * 
	 * @generated
	 */
	private String password;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public FoodApp() {
		super();
	}
	/**
	 * The documentation of the method login.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String login() {
		// Start of user code for the body of login
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getUsername.
	 * 
	 * @generated
	 */
	public String getUsername() {
		return this.username;
	}
	
	/**
	 * The documentation of the setter setUsername.
	 * 
	 * @generated
	 */
	public void setUsername(String newUsername) {
		this.username = newUsername;
	}
	
	/**
	 * The documentation of the getter getPassword.
	 * 
	 * @generated
	 */
	public String getPassword() {
		return this.password;
	}
	
	/**
	 * The documentation of the setter setPassword.
	 * 
	 * @generated
	 */
	public void setPassword(String newPassword) {
		this.password = newPassword;
	}
}
