/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.RM2PT.acceleo.foodapp.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Order
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Order {
	/**
	 * The documentation of the attribute quantity.
	 * 
	 * @generated
	 */
	private Integer quantity;
	
	/**
	 * The documentation of the attribute foodType.
	 * 
	 * @generated
	 */
	private String foodType;
	
	/**
	 * The documentation of the attribute price.
	 * 
	 * @generated
	 */
	private Integer price;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Order() {
		super();
	}
	/**
	 * The documentation of the method placeOrder.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String placeOrder() {
		// Start of user code for the body of placeOrder
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getQuantity.
	 * 
	 * @generated
	 */
	public Integer getQuantity() {
		return this.quantity;
	}
	
	/**
	 * The documentation of the setter setQuantity.
	 * 
	 * @generated
	 */
	public void setQuantity(Integer newQuantity) {
		this.quantity = newQuantity;
	}
	
	/**
	 * The documentation of the getter getFoodType.
	 * 
	 * @generated
	 */
	public String getFoodType() {
		return this.foodType;
	}
	
	/**
	 * The documentation of the setter setFoodType.
	 * 
	 * @generated
	 */
	public void setFoodType(String newFoodType) {
		this.foodType = newFoodType;
	}
	
	/**
	 * The documentation of the getter getPrice.
	 * 
	 * @generated
	 */
	public Integer getPrice() {
		return this.price;
	}
	
	/**
	 * The documentation of the setter setPrice.
	 * 
	 * @generated
	 */
	public void setPrice(Integer newPrice) {
		this.price = newPrice;
	}
}
