/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.RM2PT.acceleo.foodapp.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Payment
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Payment {
	/**
	 * The documentation of the attribute type.
	 * 
	 * @generated
	 */
	private String type;
	
	/**
	 * The documentation of the attribute amount.
	 * 
	 * @generated
	 */
	private Integer amount;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Payment() {
		super();
	}
	/**
	 * The documentation of the method payment.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public Boolean payment() {
		// Start of user code for the body of payment
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getType.
	 * 
	 * @generated
	 */
	public String getType() {
		return this.type;
	}
	
	/**
	 * The documentation of the setter setType.
	 * 
	 * @generated
	 */
	public void setType(String newType) {
		this.type = newType;
	}
	
	/**
	 * The documentation of the getter getAmount.
	 * 
	 * @generated
	 */
	public Integer getAmount() {
		return this.amount;
	}
	
	/**
	 * The documentation of the setter setAmount.
	 * 
	 * @generated
	 */
	public void setAmount(Integer newAmount) {
		this.amount = newAmount;
	}
}
