<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OrderHistory">

  <eClassifiers xsi:type="ecore:EClass" name="CustomerRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" 
                        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
                        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="OrderRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
                        eType="#//CustomerRecord"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1" 
                        eType="#//OrderItemRecord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"  
                        eType="#//OrderStatus"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="OrderItemRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dish" lowerBound="1"
                        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"  
                        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EEnum" name="OrderStatus">  
    <eLiterals name="Pending" literal="1"/>
    <eLiterals name="InTransit"  literal="2"/>
    <eLiterals name="Delivered" literal="3"/>
  </eClassifiers>
  
</ecore:EPackage>